### PR TITLE
Uses ports for a self documenting code

### PR DESCRIPTION
**Pull request by enjoythelive1**
I changed this in my exploration of Arduino Uno. I wanted to explore the capabilities of ruduino and I found this nice abstractions that may be more beginner friendly.

### CODE REVIEW

**Comment by dylanmckay** [comment]
This change looks good - could you please rebase it?

**Comment by enjoythelive1** [comment]
Sure.

I tried to build, but not even `master` compiles correctly. It complains about the core not existing:

```
 ✘ arturo@arturos-dell-xps  ~/Arduino/blink   master ±  cargo build
   Compiling blink v0.1.0 (/home/arturo/Arduino/blink)
error[E0432]: unresolved import `ruduino::cores::atmega328p`
 --> src/main.rs:6:5
  |
6 | use ruduino::cores::atmega328p as avr_core;
  |     ^^^^^^^^^^^^^^^^----------^^^^^^^^^^^^
  |     |               |
  |     |               help: a similar name exists in the module: `atmega328`
  |     no `atmega328p` in `cores`

error[E0433]: failed to resolve: use of undeclared type `DDRB`
  --> src/main.rs:14:5
   |
14 |     DDRB::set_mask_raw(0xFFu8);
   |     ^^^^ not found in this scope
   |
help: consider importing this struct
   |
6  | use ruduino::cores::atmega328::DDRB;
   |

error[E0433]: failed to resolve: use of undeclared type `PORTB`
  --> src/main.rs:18:9
   |
18 |         PORTB::set_mask_raw(0xFF);
   |         ^^^^^ not found in this scope
   |
help: consider importing this struct
   |
6  | use ruduino::cores::atmega328::PORTB;
   |

error[E0433]: failed to resolve: use of undeclared type `PORTB`
  --> src/main.rs:23:9
   |
23 |         PORTB::unset_mask_raw(0xFF);
   |         ^^^^^ not found in this scope
   |
help: consider importing this struct
   |
6  | use ruduino::cores::atmega328::PORTB;
   |

warning: unused import: `ruduino::Register`
 --> src/main.rs:7:5
  |
7 | use ruduino::Register;
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: language item required, but not found: `eh_personality`

error: `#[panic_handler]` function required, but not found

error: aborting due to 6 previous errors; 1 warning emitted

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `blink`

To learn more, run the command again with --verbose.

```

And when I roll back 1693249f it complains about the `panic_handler`:
```
 ✘ arturo@arturos-dell-xps  ~/Arduino/blink   master ±  cargo build
   Compiling blink v0.1.0 (/home/arturo/Arduino/blink)
error: language item required, but not found: `eh_personality`

error: `#[panic_handler]` function required, but not found

error: aborting due to 2 previous errors

error: could not compile `blink`

To learn more, run the command again with --verbose.
```

I cleared the cargo cache, updated the lock file, and deleted all the cargo registry in my PC and it failed anyway.

I can merge it even if it is not working, but I would rather make sure it works.

**Comment by stappersg** [comment]
Yes, much changed since the original Merge Request. It is what new technology makes interesting. @enjoythelive1 please give the MR another part of your time.

**Comment by enjoythelive1** [comment]
I still fail to build it but it probably has to do something with my LLVM setup. I will try to make sure I can build it correctly, but I hope the gitaction can bould it succesfully.

**Comment by stappersg** [comment]
Yes, succes.

image

**Pull request merged**
